#!/usr/bin/env ansible-playbook
---
- hosts: all
  become: true

  vars_files:
    - custom.yml
    - secret.yml

  handlers:
    - import_tasks: handlers/main.yml

  pre_tasks:
    - set_fact:
        aws: "{{ lookup('ansible.builtin.env', 'AWS_EC2') == 'true' }}"
        letsencrypt_staging: "{{ [lookup('ansible.builtin.env', 'LETSENCRYPT_STAGING') | lower | default('no')] }}"

  roles:
    - role: petra
      tags:
        - petra
