---
- name: Make sure the dinamic-site container is created and running
  community.docker.docker_container:
    name: dinamic-site
    image: prakhar1989/static-site
    networks:
      - name: dinamic-site
        ipv4_address: 10.8.2.6
    state: 'started'
    restart_policy: unless-stopped
